// <auto-generated />
namespace RMMS.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class student_teacher_AcademicResult_Subject : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(student_teacher_AcademicResult_Subject));
        
        string IMigrationMetadata.Id
        {
            get { return "201908031435099_student_teacher_AcademicResult_Subject"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
